### ISSUE TITLE
Creating a workshop repo with lessons embedded in it

### ISSUE THREAD

**Issue by jonjab** [UCSBCarpentry/2020-01-17-UCSB-bash#1]
We've made this repo from the canonical workshop template.  Now we are at the point where we want to insert individual lessons and episodes.  I moved the Bash lesson .md files into the _episodes folder, but we are at the same impasse we were in November -- the site does not re-build itself

**Comment by ilessing** [comment]
I cloned the repo to my local workstation and ran `make serve` and got the following error:

```
.gem/ruby/2.3.0/gems/bundler-2.0.1/lib/bundler/resolver.rb
:287:in `block in verify_gemfile_dependencies_are_found!': 
Could not find gem 'github-pages' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
```

so I deleted the `Gemfile` that Francois Michonneau added dec 10 and then I was able to run 
`make serve` without any errors.
I don't know why the `Gemfile` was added but I think I'll delete it.

**Comment by ilessing** [comment]
that seems to have fixed it.  https://ucsbcarpentry.github.io/2020-01-17-UCSB-bash/ is built now.

**Comment by jonjab** [comment]
FWIW, on a Carpentry call yesterday morning an experienced instructor told me that she doesn't bother moving the individual lessons into the workshop template.  She works from a local, customized, community fork of the canonical lessons.  Big community at UW Madison tho.

**Comment by jonjab** [comment]
And even without that gem file, the episodes we dropped in on Monday aren't showing.

https://ucsbcarpentry.github.io/2020-01-17-UCSB-bash/01-intro/

Gives a 404

But I'm keeping this closed.
