### ISSUE TITLE
Missing from navigation menu: Setup, Episodes and Extras

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/2020-01-17-UCSB-bash#4]

**Comment by torwhite** [comment]
"If several Markdown files are stored in a directory whose name begins with an underscore, Jekyll creates a collection for them. We rely on this for both lesson episodes (stored in _episodes) and extra files (stored in _extras). For example, putting the extra files in _extras allows us to populate the “Extras” menu pulldown automatically. To clarify what will appear where, we store files that appear directly in the navigation bar in the root directory of the lesson." from https://carpentries.github.io/lesson-example/02-tooling/index.html 

check files in: 
_extras/: extra pages 
_episodes/: lesson episodes 
_episodes_rmd/: R Markdown lesson episodes (if any).
code/: for code samples.
data/: for data files.
fig/: for figures and other images.
files/: for miscellaneous files.

**Comment by torwhite** [comment]
added missing files to data, fig, and files. Nothing in code for unix shell. episodes_rmd also irrelevant here. We updated episodes yesterday. Added missing files to _extras (should be pages in the drop-down menu). Added manual_episode_order.html, aio-script.md from canonical and updated navbar.html in hopes it would fix the missing navigation menu items, no dice.

**Comment by ilessing** [comment]
What's the URL where the navigation menus are missing?
Do you have a URL of a similar workshop where the menus are present that I could look at as a model for what is should be like?

**Comment by torwhite** [comment]
I was thinking of the navigation bars that are in the canonical lessons like at http://swcarpentry.github.io/shell-novice/ with dropdowns for extras and episodes. I was chatting with Jon about it yesterday and he said that's the case with all our workshops. I don't know if it's a workshop vs. lesson thing or something else.

**Comment by torwhite** [comment]
Ok, using Madison as an example again: https://uw-madison-datascience.github.io/2019-01-14-uwmadison-swc/ . Looks like they have the navigation options we're missing in our workshops.  Maybe a minor thing in the end, but would be nice for usability.

**Comment by ilessing** [comment]
![SWcarpentryEpisodesScreen-Shot-2019-12-17](https://user-images.githubusercontent.com/275899/71045307-57c1aa00-20e9-11ea-8fc6-8c9b5fbee540.png)
That episodes menu is nice.  How did they do that?  LOL

**Comment by ilessing** [comment]
fixed with 4585342    (see commit for details)

  We should now have an Episodes menu at: https://ucsbcarpentry.github.io/2020-01-17-UCSB-bash/

![ucsbCarpentryScreen-Shot-2019-12-17](https://user-images.githubusercontent.com/275899/71046332-d66c1680-20ec-11ea-9a74-ca6a40624846.png)
